# Generated by Django 2.0 on 2018-01-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='contact_name',
            field=models.CharField(default='rabble', max_length=256),
        ),
    ]
