# Generated by Django 2.0 on 2018-01-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contacts_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='company_name',
            field=models.CharField(default='rabble', max_length=250),
        ),
        migrations.AddField(
            model_name='contacts',
            name='phone_ext',
            field=models.CharField(blank='True', default='rabble', max_length=10),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
