# Generated by Django 2.0 on 2018-02-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20180126_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='company_name',
            field=models.CharField(default='company name', max_length=250),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='contact_name',
            field=models.CharField(default='contact name', max_length=256),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone_ext',
            field=models.CharField(blank='True', default='ext', max_length=10),
        ),
    ]
