# Generated by Django 2.0.2 on 2018-02-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20180221_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='company_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='contact_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone_ext',
            field=models.CharField(blank='True', max_length=10),
        ),
    ]
