# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(max_length=256)),
                ('address', models.TextField()),
                ('contact_number', models.TextField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('company_url', models.URLField()),
                ('about', models.TextField()),
            ],
        ),
    ]
