# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditrequest',
            name='contact_name',
            field=models.TextField(default='Contact', max_length=100),
        ),
        migrations.AlterField(
            model_name='auditrequest',
            name='contact_number',
            field=models.TextField(max_length=50),
        ),
    ]
