# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0002_auto_20171115_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditrequest',
            name='address',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='auditrequest',
            name='company_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='auditrequest',
            name='contact_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='auditrequest',
            name='contact_number',
            field=models.CharField(max_length=50),
        ),
    ]
