# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 04:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0003_auto_20171115_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditrequest',
            old_name='about',
            new_name='Tell_Us_About_Your_Needs',
        ),
        migrations.RenameField(
            model_name='auditrequest',
            old_name='company_url',
            new_name='company_URL',
        ),
    ]
