# Generated by Django 2.0 on 2018-02-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0004_auto_20171115_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditrequest',
            name='company_URL',
            field=models.CharField(max_length=256),
        ),
    ]
